version: '3'
services:
  web_server:
    container_name: web-server
    build: 
      context: ./web-server
      dockerfile: ./Dockerfile
    environment:
      NODE_ENV: production
      REDIS_URL: redis://172.31.8.80
      DB_DATABASE: tick
      DB_HOST: tick.cvtqwu3zlk3i.ap-northeast-1.rds.amazonaws.com:3306
      DB_USER: admin
      DB_PASSWORD: tick000
    ports:
      - 127.0.0.1:8000:8000
    restart: always
